server:
  port: 8082

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  cloud:
    function:
      definition: inventoryProcessor
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
      bindings:
        inventoryProcessor-in-0:
          destination: order.created
          content-type: application/json
          group: inventory-service-group
        inventoryProcessor-out-0:
          destination: inventory.events
          content-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.orderprocessing: INFO
